# Get all groups
GET http://localhost:5253/api/Groups

###

# Create a new group
POST http://localhost:5253/api/Groups
Content-Type: application/json

{
    "name": "Test Group",
    "description": "This is a test group"
}

###

# Get group by ID
GET http://localhost:5253/api/Groups/1

###

# Update group
PUT http://localhost:5253/api/Groups/1
Content-Type: application/json

{
    "id": 1,
    "name": "Updated Group",
    "description": "This is an updated group"
}

###

# Delete group
DELETE http://localhost:5253/api/Groups/1